-- insert users
INSERT INTO
    users (
        first_name,
        last_name,
        email,
        role,
        password
    )
VALUES (
        'Admin',
        'System',
        'admin@dailydrinks.com',
        'admin',
        '$2a$12$lJ2euHwJ1FgA3QRN59Zfze0RQ6uRRE2fVxq4QQbCkqpVcnwdvw43S'
    ),
    (
        'Itsna',
        'Maulana',
        'itsna@gmail.com',
        'customer',
        '$2a$12$lJ2euHwJ1FgA3QRN59Zfze0RQ6uRRE2fVxq4QQbCkqpVcnwdvw43S'
    ),
    (
        'Hasan',
        'Maulana',
        'hasan@gmail.com',
        'customer',
        '$2a$12$lJ2euHwJ1FgA3QRN59Zfze0RQ6uRRE2fVxq4QQbCkqpVcnwdvw43S'
    );

-- insert categories
INSERT INTO
    categories (name, created_by, updated_by)
VALUES ('smoothies', 1, 1),
    ('juices', 1, 1),
    ('drinks', 1, 1),
    ('foods', 1, 1);

-- insert sizes
INSERT INTO
    sizes (name, created_by, updated_by)
VALUES ('R', 1, 1),
    ('L', 1, 1),
    ('XL', 1, 1),
    ('250gr', 1, 1);

-- insert products
INSERT INTO
    products (
        name,
        description,
        price,
        discount_percent,
        rating,
        is_flash_sale,
        stock,
        is_active,
        created_by,
        updated_by
    )
VALUES (
        'The Emerald Boost (Green Smoothie)',
        'Start your day with a burst of green energy! *The Emerald Boost* is a perfect blend of fresh spinach, ripe banana for natural sweetness, tropical mango, and a hint of ginger for a refreshing, warm sensation. Blended smoothly with coconut water for maximum hydration, this drink is the easiest and quickest way to get your daily greens intake.',
        32000,
        NULL,
        4.0,
        false,
        2,
        true,
        1,
        1
    ),
    (
        'Ruby Cleanse (Detox Juice)',
        'Experience a deep cleanse from within with *Ruby Cleanse*. This juice combines the detoxifying power of beets, the sweetness of carrots and apples, and a touch of lemon for freshness. The deep ruby ​​color signifies its richness in antioxidants that help your body fight free radicals. Perfect for rebooting your system.',
        38000,
        NULL,
        3.0,
        false,
        2,
        true,
        1,
        1
    ),
    (
        'Golden Immunity (Tonic Drink)',
        'Make Golden Immunity your daily shield. This warming drink is a powerful blend of fresh turmeric, ginger, freshly squeezed orange juice, and a pinch of black pepper to maximize curcumin absorption. Functions as a natural anti-inflammatory and a powerful immune system booster.',
        45000,
        33.33,
        5.0,
        true,
        2,
        true,
        1,
        1
    ),
    (
        'Post-Workout Power (Protein Shake)',
        'Replenish your energy and repair your muscles after a workout with Post-Workout Power. A blend of chocolate-flavored plant-based protein, frozen banana for a creamy texture, natural peanut butter for healthy fats, and oat milk. It tastes as delicious as a milkshake, but is specifically designed to support your fitness goals.',
        52000,
        28.85,
        5.0,
        true,
        2,
        true,
        1,
        1
    ),
    (
        'Berry Glow Smoothie',
        'Get radiant skin that glows from within! *Berry Glow Smoothie* is a blend of antioxidant-rich berries (strawberries, blueberries, raspberries) blended with banana, chia seeds, and almond milk. This delicious drink helps nourish your skin and leaves it looking fresher and more radiant.',
        44000,
        NULL,
        4.0,
        false,
        2,
        true,
        1,
        1
    ),
    (
        'Moonlight Latte (Calming Drink)',
        'Unwind after a long day with a *Moonlight Latte*. This calming, caffeine-free drink is made with butterfly pea flowers, which produce a beautiful purplish-blue color, warm oat milk, a hint of honey, and a pinch of cinnamon. It''s the perfect companion for unwinding before bed.',
        36000,
        22.22,
        5.0,
        true,
        2,
        true,
        1,
        1
    ),
    (
        'Hydra Green (Hydrating Juice)',
        'Quench your thirst in the healthiest way. *Hydra Green* is a very light and hydrating juice made with cucumber, celery, green apple, and fresh mint leaves. With very low calories, this drink is an ideal choice for staying hydrated throughout the day without guilt.',
        28000,
        NULL,
        5.0,
        true,
        2,
        true,
        1,
        1
    ),
    (
        'Tropical Vitality',
        'Experience a tropical vacation in one glass! *Tropical Vitality* is a refreshing blend of sweet mango, vitamin C-rich pineapple, and exotic passion fruit, blended with pure coconut water. This drink is not only delicious, but also provides an instant, natural energy boost.',
        40000,
        27.50,
        5.0,
        true,
        2,
        true,
        1,
        1
    ),
    (
        'Sunrise Chicory Latte',
        'Looking for a caffeine-free coffee experience? Try the *Sunrise Chicory Latte*. Roasted chicory root delivers a rich, slightly bitter, coffee-like flavor, paired with warm almond milk and a hint of natural sweetener. It provides focused energy in the morning without the jitters of caffeine.',
        36000,
        11.11,
        5.0,
        true,
        2,
        true,
        1,
        1
    ),
    (
        'Dragon''s Kiss Smoothie',
        'A drink as beautiful as it tastes. The *Dragon''s Kiss Smoothie* gets its bright pink color from real dragon fruit (pitaya), blended with strawberries, bananas, and coconut milk for a creamy, exotic flavor. Rich in fiber and antioxidants, this smoothie is excellent for digestion and overall health.',
        42000,
        28.57,
        5.0,
        true,
        2,
        true,
        1,
        1
    ),
    (
        'Classic Açaí Bowls',
        'Dive into the ultimate superfood experience! Our Classic Açaí Bowl features organic açaí berries from the Amazon, blended to perfection and topped with fresh granola, sliced bananas, strawberries, and a drizzle of honey. Packed with antioxidants and natural energy, this bowl is your perfect breakfast or post-workout fuel that tastes like a guilt-free dessert.',
        48000,
        NULL,
        5.0,
        false,
        15,
        true,
        1,
        1
    ),
    (
        'Middle Eastern Grilled Vegetable & Lentil Bowls with Falafel-Spiced Roasted Chickpeas & Tahini-Yogurt Sauce',
        'Transport your taste buds to the Mediterranean! This vibrant bowl combines smoky grilled vegetables with protein-rich lentils, crispy falafel-spiced chickpeas, and a creamy tahini-yogurt sauce that ties everything together. Every bite delivers a perfect balance of textures and authentic Middle Eastern flavors that will leave you craving more.',
        55000,
        NULL,
        4.8,
        false,
        12,
        true,
        1,
        1
    ),
    (
        'Barbacoa Beef Bowls',
        'Indulge in bold Mexican flavors without the guilt! Tender, slow-cooked barbacoa beef sits atop a bed of cilantro-lime rice, black beans, fresh pico de gallo, and creamy avocado. This protein-packed bowl delivers authentic taste with quality ingredients that fuel your body and satisfy your cravings.',
        62000,
        10.0,
        4.7,
        true,
        10,
        true,
        1,
        1
    ),
    (
        'Banh Mi-Less Banh Mi Bowl',
        'All the incredible flavors of Vietnam''s favorite sandwich, deconstructed into a healthier bowl! Enjoy marinated protein with pickled vegetables, fresh cilantro, jalapeños, and a zesty lime dressing over brown rice or vermicelli noodles. It''s a refreshing fusion of tangy, spicy, and savory that keeps you coming back for more.',
        52000,
        NULL,
        4.6,
        false,
        14,
        true,
        1,
        1
    ),
    (
        'Nourishing Quinoa Bowl',
        'Pure nourishment in every spoonful! This wholesome bowl features fluffy quinoa topped with roasted seasonal vegetables, leafy greens, avocado, and your choice of protein, finished with a light lemon-tahini dressing. It''s a complete meal that provides sustained energy and leaves you feeling satisfied and revitalized.',
        50000,
        NULL,
        4.5,
        false,
        18,
        true,
        1,
        1
    ),
    (
        'Chicken Enchilada Bowls',
        'Experience the comfort of enchiladas in a healthier format! Seasoned grilled chicken, black beans, roasted corn, and melted cheese sit on a base of cilantro-lime rice, topped with enchilada sauce, sour cream, and fresh cilantro. This bowl delivers all the cozy Mexican flavors you love with better-for-you ingredients.',
        54000,
        15.0,
        4.8,
        true,
        11,
        true,
        1,
        1
    ),
    (
        'Berry Beet Acai Breakfast Bowls',
        'Start your morning with a burst of color and nutrition! This stunning breakfast bowl blends antioxidant-rich açaí with earthy beets and sweet berries, creating a naturally vibrant base. Topped with crunchy granola, fresh berries, coconut flakes, and chia seeds, it''s a breakfast that energizes your body and delights your eyes.',
        46000,
        NULL,
        4.9,
        false,
        16,
        true,
        1,
        1
    ),
    (
        'Black Bean Burrito Bowl',
        'A plant-powered feast that doesn''t compromise on flavor! Seasoned black beans, cilantro-lime rice, fresh salsa, guacamole, corn, and crispy tortilla strips come together in perfect harmony. High in fiber and protein, this bowl keeps you full and satisfied while delivering authentic Mexican taste in every bite.',
        45000,
        NULL,
        4.4,
        false,
        20,
        true,
        1,
        1
    ),
    (
        'Vietnamese BBQ Shrimp Noodle Bowl',
        'Escape to the streets of Saigon with every forkful! Succulent BBQ shrimp glazed with lemongrass and garlic sit atop rice noodles, fresh herbs, crunchy vegetables, and crushed peanuts, all brought together with a tangy fish sauce dressing. Light yet satisfying, this bowl is a refreshing explosion of Vietnamese flavors.',
        58000,
        NULL,
        4.7,
        false,
        13,
        true,
        1,
        1
    ),
    (
        'Peanut Butter & Jelly Breakfast Bowl',
        'Your childhood favorite, reimagined for a healthier you! Creamy oatmeal swirled with natural peanut butter and topped with fresh berry compote, sliced bananas, and a sprinkle of chia seeds. It''s nostalgic comfort food that actually fuels your morning with protein, fiber, and natural sweetness.',
        42000,
        NULL,
        4.6,
        false,
        17,
        true,
        1,
        1
    ),
    (
        'Crunchy Quinoa Power Bowl with Almond Ginger Dressing',
        'Unleash your inner power with this nutrient-dense masterpiece! Protein-rich quinoa meets crispy chickpeas, roasted vegetables, fresh greens, and avocado, all elevated by a zingy almond ginger dressing. The combination of textures and flavors makes healthy eating an absolute pleasure while keeping you energized all day.',
        51000,
        NULL,
        4.8,
        false,
        15,
        true,
        1,
        1
    ),
    (
        'Chopped Chicken Sesame Noodle Bowls',
        'Asian fusion at its finest! Tender chopped chicken mingles with colorful vegetables and chewy noodles, all tossed in a rich sesame-soy sauce and topped with toasted sesame seeds and scallions. This bowl delivers restaurant-quality flavor with wholesome ingredients that satisfy your Asian food cravings the healthy way.',
        53000,
        NULL,
        4.7,
        false,
        14,
        true,
        1,
        1
    ),
    (
        'Vegetarian Mixed Rice Bowl-Bibimbap',
        'Experience Korea''s most beloved dish in all its colorful glory! An artful arrangement of seasoned vegetables, mushrooms, crispy tofu, and a perfectly fried egg sits atop warm rice, served with spicy gochujang sauce on the side. Mix it all together for a harmonious blend of flavors, textures, and nutrients that nourish body and soul.',
        49000,
        NULL,
        4.9,
        false,
        16,
        true,
        1,
        1
    ),
    (
        '7 Spice Teriyaki Chicken Rice Bowls',
        'Bold flavors meet balanced nutrition! Juicy chicken glazed with our signature 7-spice teriyaki sauce sits on fluffy rice alongside steamed broccoli, edamame, and sesame seeds. This Japanese-inspired bowl delivers the perfect combination of sweet, savory, and umami that makes healthy eating absolutely delicious.',
        52000,
        12.0,
        4.6,
        true,
        13,
        true,
        1,
        1
    ),
    (
        'Taco Wannabe Mexican Breakfast Bowl',
        'Wake up to fiesta flavors! Scrambled eggs, seasoned black beans, roasted sweet potatoes, fresh salsa, avocado, and a sprinkle of cheese create the ultimate Mexican-inspired breakfast. It''s a protein-packed morning meal that energizes your day while satisfying those taco cravings in a healthier, more nourishing format.',
        44000,
        NULL,
        4.5,
        false,
        19,
        true,
        1,
        1
    ),
    (
        'Grilled Chicken Kebab Bowls with Cucumber Salad and Tzatziki',
        'A Mediterranean escape in a bowl! Perfectly seasoned grilled chicken kebabs rest on fluffy couscous or rice, accompanied by refreshing cucumber salad, juicy tomatoes, and creamy homemade tzatziki sauce. Light, fresh, and bursting with herbs and spices, this bowl transports you to a Greek island with every bite.',
        56000,
        NULL,
        4.8,
        false,
        12,
        true,
        1,
        1
    ),
    (
        'Butter-Toasted Oat Breakfast Bowls',
        'Elevate your morning routine with this cozy comfort bowl! Oats toasted in real butter deliver a rich, nutty flavor that''s topped with caramelized bananas, a drizzle of maple syrup, crunchy pecans, and a dash of cinnamon. It''s breakfast that feels indulgent but nourishes you with whole grains and natural ingredients.',
        40000,
        NULL,
        4.4,
        false,
        18,
        true,
        1,
        1
    ),
    (
        'Black Bean and Avocado Power Bowl',
        'Simple ingredients, extraordinary nutrition! This plant-based powerhouse combines protein-rich black beans with creamy avocado, quinoa, roasted vegetables, and a zesty lime dressing. Perfect for vegans and health enthusiasts, this bowl proves that clean eating can be incredibly satisfying and delicious.',
        47000,
        NULL,
        4.7,
        false,
        17,
        true,
        1,
        1
    ),
    (
        'Blueberry Farro Yogurt Bowl',
        'Ancient grains meet modern wellness! Nutty farro provides a hearty base topped with creamy Greek yogurt, fresh blueberries bursting with antioxidants, crunchy granola, and a drizzle of honey. This bowl offers the perfect balance of complex carbs, protein, and natural sweetness to fuel your morning or afternoon.',
        43000,
        NULL,
        4.6,
        false,
        16,
        true,
        1,
        1
    ),
    (
        'Fish Taco Cabbage Bowl',
        'Coastal flavors without the carbs! Flaky, seasoned white fish sits on a bed of crunchy cabbage slaw, topped with fresh pico de gallo, creamy avocado, and a zesty lime crema. Light yet satisfying, this deconstructed fish taco delivers all the beachy vibes and fresh flavors you crave in a nutrient-packed format.',
        54000,
        NULL,
        4.5,
        false,
        14,
        true,
        1,
        1
    ),
    (
        'Cuban Chicken and Black Bean Quinoa Bowls with Fried Chili Spiced Bananas',
        'Take your taste buds on a Caribbean adventure! Citrus-marinated Cuban chicken pairs beautifully with seasoned black beans and fluffy quinoa, but the star is the caramelized chili-spiced bananas that add an unexpected sweet-savory twist. This exotic bowl is a flavor journey that''s as exciting as it is nourishing.',
        57000,
        NULL,
        4.8,
        false,
        11,
        true,
        1,
        1
    ),
    (
        'Thai Tofu Quinoa Bowls',
        'Plant-based perfection with Thai flair! Crispy tofu glazed in a sweet and tangy sauce sits atop protein-rich quinoa with fresh vegetables, crushed peanuts, and fresh cilantro, all tied together with a spicy peanut-lime dressing. Every bite delivers authentic Thai flavors while keeping things light and wholesome.',
        50000,
        NULL,
        4.7,
        false,
        15,
        true,
        1,
        1
    ),
    (
        'Spicy Sweet Potato & Green Rice Burrito Bowls',
        'Heat meets sweet in this vibrant creation! Roasted sweet potatoes caramelized to perfection pair with cilantro-infused green rice, black beans, corn, and a spicy chipotle sauce that brings the heat. Topped with cooling avocado and lime crema, this bowl is a flavor rollercoaster that leaves you satisfied and energized.',
        48000,
        NULL,
        4.6,
        false,
        16,
        true,
        1,
        1
    ),
    (
        'Chicken & Quinoa Bowl with Veggies',
        'Clean eating made simple and delicious! Lean grilled chicken breast, fluffy quinoa, and a rainbow of fresh seasonal vegetables come together with a light herb dressing. This wholesome bowl is perfect for meal prep or a quick, nutritious lunch that fuels your body without weighing you down.',
        49000,
        NULL,
        4.5,
        false,
        20,
        true,
        1,
        1
    ),
    (
        'Chocolate Hazelnut Smoothie Bowl',
        'Dessert for breakfast? Yes, please! This decadent smoothie bowl blends frozen bananas with rich cacao and hazelnut butter for a Nutella-like flavor that''s naturally sweetened and nutrient-dense. Topped with granola, fresh berries, and cacao nibs, it''s a guilt-free indulgence that satisfies your sweet tooth while nourishing your body.',
        46000,
        NULL,
        4.9,
        false,
        18,
        true,
        1,
        1
    ),
    (
        'Honey Beary',
        'Nature''s perfect sweetness in a glass! Creamy almond milk blends with ripe banana, antioxidant-rich blueberries, protein-packed peanut butter, and golden Texas wildflower honey for a smoothie that''s naturally sweet and incredibly satisfying. It''s like a liquid hug that energizes your day with wholesome ingredients.',
        38000,
        NULL,
        4.7,
        false,
        25,
        true,
        1,
        1
    ),
    (
        'Morning Sunshine',
        'Greet the day with tropical energy! This vibrant smoothie combines the brightness of pineapple and orange with creamy banana, sweet mango, and superfoods like goji berries and local bee pollen. Each sip delivers a burst of vitamin C and natural vitality that makes you feel like you''re sipping sunshine on a beach.',
        40000,
        NULL,
        4.8,
        false,
        22,
        true,
        1,
        1
    ),
    (
        'Berry Godmother',
        'The ultimate berry blessing! This antioxidant powerhouse blends pineapple with a medley of strawberries, blueberries, raspberries, and goji berries for a smoothie that''s as beautiful as it is beneficial. Sweet, tangy, and bursting with flavor, it''s your fairy godmother granting wishes for glowing skin and sustained energy.',
        42000,
        NULL,
        4.9,
        false,
        20,
        true,
        1,
        1
    ),
    (
        'Rehydrator',
        'The ultimate post-workout recovery drink! Hydrating watermelon and coconut oil blend with raspberry, mango, peach, and earthy beet, enhanced with refreshing mint, zesty lime, and a pinch of sea salt to replenish electrolytes. This smoothie quenches your thirst while restoring your body with natural goodness.',
        41000,
        NULL,
        4.6,
        false,
        18,
        true,
        1,
        1
    ),
    (
        'Clementine',
        'Pure citrus bliss! This sunshine-in-a-cup smoothie combines juicy orange with tropical pineapple, sweet mango, and peachy goodness for a vitamin C explosion that brightens your mood and boosts your immunity. Light, refreshing, and naturally sweet, it''s like summer captured in a glass.',
        39000,
        NULL,
        4.5,
        false,
        24,
        true,
        1,
        1
    ),
    (
        'Originator',
        'The OG of smoothies, perfected! Crisp apple and creamy almond milk blend with banana, blueberries, tart cherries, rich peanut butter, and blue-green spirulina, with your choice of protein powder. This balanced smoothie delivers everything you need for sustained energy, muscle recovery, and overall wellness in one delicious package.',
        45000,
        20.0,
        4.8,
        true,
        16,
        true,
        1,
        1
    ),
    (
        'Wild Child',
        'Unleash your adventurous side! Exotic dragon fruit and tropical pineapple blend with creamy banana, sweet mango, zesty lime, energizing maca, coconut oil, and pea protein for a vibrant pink smoothie that''s as wild as it is nourishing. Perfect for those who dare to live boldly and fuel their adventures.',
        47000,
        NULL,
        4.9,
        false,
        15,
        true,
        1,
        1
    ),
    (
        'Home Run',
        'Simple, classic, perfection! This nostalgic blend of crisp apple, creamy banana, and sweet strawberries proves that sometimes the basics are all you need. Light, naturally sweet, and beloved by all ages, it''s a reliable hit that never strikes out on flavor or nutrition.',
        35000,
        NULL,
        4.4,
        false,
        28,
        true,
        1,
        1
    ),
    (
        'The Levitator',
        'Rise above with this ethereal creation! Exotic dragon fruit meets blue majik spirulina for a stunning blue-pink gradient, blended with passion fruit, pineapple, mango, and fresh ginger, served ice-cold. This Instagram-worthy juice not only looks magical but delivers powerful antioxidants and natural energy that truly lifts your spirits.',
        48000,
        NULL,
        5.0,
        false,
        12,
        true,
        1,
        1
    ),
    (
        'Pleasant Valley',
        'A refreshing escape to citrus paradise! This bright and cheerful juice combines freshly squeezed orange with hydrating watermelon, tropical pineapple, tart lemon, and zesty lime. Each sip is a burst of sunshine that hydrates, revitalizes, and fills you with good vibes and vitamin C.',
        40000,
        NULL,
        4.7,
        false,
        20,
        true,
        1,
        1
    ),
    (
        'Ninja Bachelor Party',
        'Sneak in your greens with a kick! This bold juice blends pineapple sweetness with celery, kale, parsley, and spinach, then adds a surprising jalapeño punch and sea salt for balance. It''s a stealthy way to flood your system with nutrients while enjoying a flavor profile that''s anything but boring.',
        42000,
        NULL,
        4.6,
        false,
        18,
        true,
        1,
        1
    ),
    (
        'Beets Mode',
        'Activate your body''s natural power! This vibrant ruby-red juice combines earthy beets with sweet orange, carrots, tart lemon, and warming ginger for a potent blend that supports circulation, boosts stamina, and detoxifies naturally. It''s your secret weapon for peak performance and glowing health.',
        44000,
        NULL,
        4.8,
        false,
        16,
        true,
        1,
        1
    ),
    (
        'Recovery Punch',
        'Your body''s best friend after any workout! Hydrating watermelon and coconut water blend with tropical pineapple, earthy beet, zesty lime, and electrolyte-rich sea salt to restore what you''ve lost. This refreshing punch helps muscles recover faster while tasting like a tropical vacation.',
        43000,
        NULL,
        4.7,
        false,
        19,
        true,
        1,
        1
    ),
    (
        'Tigerlilly',
        'Pure green power, refined! This elegant juice combines cucumber''s hydration with celery''s crispness, kale''s nutrients, parsley''s freshness, and spinach''s iron-rich goodness. Clean, light, and incredibly refreshing, it''s the perfect way to flood your body with chlorophyll and feel naturally energized.',
        41000,
        NULL,
        4.5,
        false,
        22,
        true,
        1,
        1
    ),
    (
        'Tree of Life',
        'Ancient wisdom in liquid form! This potent elixir blends creamy coconut with sweet carrot, earthy beet, anti-inflammatory turmeric and ginger, zesty lime, and a kick of cayenne. Each sip delivers powerful healing properties that support immunity, reduce inflammation, and awaken your body''s natural vitality.',
        46000,
        NULL,
        4.9,
        false,
        14,
        true,
        1,
        1
    );